#!/bin/sh
# launch gnome connection manager in english
export LANG=en_US.UTF-8  
export LANGUAGE=en_US:en  
export LC_CTYPE="en_US.UTF-8"  
/usr/share/gnome-connection-manager/gnome_connection_manager.py
