#!/bin/sh
#
# routes from host to docker host and to gns3 emulated
# environment
#
export GNS3NETWORK=10.123.0.0
export GNS3NETMASK=255.255.0.0
CID=`docker ps | grep gns3-large | awk '{print $1}'`
echo Container ID: $CID
CIDIP=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' $CID`
echo Container IP: $CIDIP
ROUTEEXIST=`netstat -nr | awk '{print $1,$3}' | grep "$GNS3NETWORK $GNS3NETMASK"`
if [ "$ROUTEEXIST" != "" ]
then
    echo "removing existing route"
    route del -net $GNS3NETWORK netmask $GNS3NETMASK
fi
echo "adding route"
route add -net $GNS3NETWORK netmask $GNS3NETMASK gw $CIDIP

